ServerRoot "/etc/httpd"
Listen 80

LoadModule jk_module modules/mod_jk.so
JkWorkersFile conf/worker.properties
JkLogFile logs/mod_jk.log
JkLogLevel info
JkMount /* ajp_worker

Timeout 1800
ProxyTimeout 1800

<VirtualHost *:80>
    ServerName localhost

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8080/ connectiontimeout=1800 timeout=1800
    ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>
