worker.list=ajp_worker

worker.ajp_worker.type=ajp13
worker.ajp_worker.host=127.0.0.1
worker.ajp_worker.port=8009
worker.ajp_worker.connection_pool_timeout=1800
worker.ajp_worker.socket_timeout=1800
worker.ajp_worker.socket_connect_timeout=1800
worker.ajp_worker.ping_mode=A
worker.ajp_worker.ping_timeout=10000
